# Generated by Django 4.1.3 on 2023-09-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(max_length=10)),
                ("class_name", models.CharField(max_length=255)),
                ("class_credit", models.IntegerField()),
                ("class_year", models.IntegerField()),
                ("semester", models.IntegerField()),
                (
                    "class_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weppage.category",
                    ),
                ),
            ],
        ),
    ]
